name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
          server-password: MAVEN_PASSWORD

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B package

      - run: mv target/coverage-reports/jacoco.exec target/coverage-reports/actions-jacoco.exec

      - name: Upload Jacoco coverage
        uses: actions/upload-artifact@v3
        with:
          name: actions-jacoco.exec
          path: target/coverage-reports/actions-jacoco.exec
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}.jar
          path: target/${{ github.event.repository.name }}.jar